# Generated by Django 2.2.6 on 2019-10-19 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20191019_1409'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
